name: ci
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
env:
    IMAGE_NAME: silverblue
    IMAGE_TAGS: latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps: 
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
        
      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ env.IMAGE_NAME }}

  build-image:
    name: Build image using Buildah action
    needs: push-ghcr
    runs-on: ubuntu-latest
    steps:
    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: |
          ./Containerfile
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
        oci: false

  push-to-registry:
    name: Push the image to GHCR (Image Registry)
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Push To GHCR
      uses: Wandalen/wretry.action@v3.5.0
      id: push
      if: github.event_name != 'pull_request'
      env:
        REGISTRY_USER: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ github.token }}
      with:
        action: redhat-actions/push-to-registry@v2
        attempt_limit: 3
        attempt_delay: 15000
        with: |
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push To GHCR
    #   uses: redhat-actions/push-to-registry@v2
    #   id: push
    #   env:
    #     REGISTRY_USER: ${{ github.actor }}
    #     REGISTRY_PASSWORD: ${{ github.token }}
    #   with:
    #     image: ${{ steps.build_image.outputs.image }}
    #     tags: ${{ steps.build_image.outputs.tags }}
    #     registry: ${{ env.IMAGE_REGISTRY }}
    #     username: ${{ env.REGISTRY_USER }}
    #     password: ${{ env.REGISTRY_PASSWORD }}
    #     extra-args: |
    #       --disable-content-trust